# Generated by Django 4.0.1 on 2022-01-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='disord_handle',
            new_name='name',
        ),
    ]
