# Generated by Django 4.0.1 on 2022-01-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_disord_handle_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
