# Generated by Django 4.0.1 on 2022-01-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
