# Generated by Django 4.0.1 on 2022-01-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_resources_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='category',
            field=models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2')], max_length=200),
        ),
    ]
