# Generated by Django 4.0.1 on 2022-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_dailytask_resources_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
