# Generated by Django 4.0.1 on 2022-01-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_dailytask_date_created_resources_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_handle', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2')], max_length=200)),
            ],
        ),
    ]
