# Generated by Django 4.0.1 on 2022-01-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
