# Generated by Django 4.0.1 on 2022-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2')], max_length=200),
        ),
    ]
