# Generated by Django 4.0.1 on 2022-01-25 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0015_staff_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='discord_handle',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
