# Generated by Django 4.0.1 on 2022-01-25 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0016_remove_staff_discord_handle_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
