# Generated by Django 4.0.1 on 2022-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_alter_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='discord_handle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
