# Generated by Django 4.0.1 on 2022-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
