# Generated by Django 4.0.1 on 2022-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_alter_customer_id_alter_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='discord_handle',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
