# Generated by Django 4.0.1 on 2022-01-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_rename_name_staff_discord_handle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
