# Generated by Django 4.0.1 on 2022-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='category',
            field=models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CP3', 'CP3')], max_length=200),
        ),
        migrations.AlterField(
            model_name='resources',
            name='category',
            field=models.CharField(blank=True, choices=[('DSA1', 'DSA1'), ('DSA2', 'DSA2'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CP3', 'CP3')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
