# Generated by Django 4.0.2 on 2022-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0028_rename_discord_handle_customer_cf_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
